### ISSUE TITLE
Duvida na parte do fluxo de autorização

### ISSUE THREAD

**Issue by christopherblosfeld** [leobaldoneto/bling-erp.js#1]
Olá brother tudo bem..
Como vc implementou o fluxo de autorizacao e como eu uso?
Acho que é a parte mais chata da API ne, quero só usar o modulo de vendas, importar valores de vendas pra criar um dashboard no meu app ...

**Comment by leobaldoneto** [comment]
A autenticação é o mais simples, pois o Bling só usa apikey e pronto. O mais chato da API deles é a paginação e o limite de requisições por minuto, mas isso só se torna um problema de você precisar puxar muitos dados.

Quais dados você precisa no dashboard?

**Comment by christopherblosfeld** [comment]
Boa noite Léo, o que eu preciso são dados simples de venda: Valor total
vendido, no dia, no mês, etc

Só pra ter uma noção mesmo e passar a utilizar a API

Em seg., 24 de jul. de 2023 17:52, Leobaldo Alcantara Neto <
***@***.***> escreveu:

**Comment by leobaldoneto** [comment]
Tenho um repositório privado com um dashboard simples e arcaico usando a lib, vou ver se amanhã ou quarta consigo preparar para compartilhar. Abaixo estão os prints:
![image](https://github.com/leobaldoneto/bling-erp.js/assets/28495813/a927fe77-2c2f-4ce4-861e-db9b22a82b98)
![image](https://github.com/leobaldoneto/bling-erp.js/assets/28495813/c54833dd-7065-4b89-a1ae-fb1924c84957)

**Comment by leobaldoneto** [comment]
Tenho um repositório privado com um dashboard simples e arcaico usando a lib, vou ver se amanhã ou quarta consigo preparar para compartilhar. Abaixo estão os prints:
![Captura de tela 2023-07-24 230407](https://github.com/leobaldoneto/bling-erp.js/assets/28495813/d61ce3b6-4324-42f7-b993-69ae68449703)
![Captura de tela 2023-07-24 230358](https://github.com/leobaldoneto/bling-erp.js/assets/28495813/e942d69e-fd77-4054-a892-38a1ba13f02e)

**Comment by christopherblosfeld** [comment]
Fechou mano, obrigado !!

Em seg., 24 de jul. de 2023 às 23:07, Leobaldo Alcantara Neto <
***@***.***> escreveu:
